In [2]:
def add(a,b):
    return a+b
print(add(2,3))

5

In [5]:
x= lambda x,y,z:x+y*z+20
print(x(10,20,30))
def statement():
    print("Lambda function work properly")
statement();

630
Lambda function work properly

In [6]:
import pandas as pd
df=pd.read_excel("D:\Download\Practice.xlsx")
df

      name  subject      fee
0  Kuldeep     Math  10000.0
1    Rahul  English      NaN
2    mohan      NaN   3839.0
3    Shyam    Hindi   3000.0
4     Aman  Science      NaN

In [7]:
df1=df.dropna()
df1

      name subject      fee
0  Kuldeep    Math  10000.0
3    Shyam   Hindi   3000.0

In [8]:
df2=df.dropna(axis=1)
print(df2)

      name
0  Kuldeep
1    Rahul
2    mohan
3    Shyam
4     Aman

In [11]:
df3=df.fillna(0)
df3

      name  subject      fee
0  Kuldeep     Math  10000.0
1    Rahul  English      0.0
2    mohan        0   3839.0
3    Shyam    Hindi   3000.0
4     Aman  Science      0.0

In [12]:
df4=df.fillna(df["fee"].mean())
df4

      name  subject      fee
0  Kuldeep     Math  10000.0
1    Rahul  English   5613.0
2    mohan   5613.0   3839.0
3    Shyam    Hindi   3000.0
4     Aman  Science   5613.0

In [13]:
df5=df.bfill()
df5

      name  subject      fee
0  Kuldeep     Math  10000.0
1    Rahul  English   3839.0
2    mohan    Hindi   3839.0
3    Shyam    Hindi   3000.0
4     Aman  Science      NaN

In [14]:
df6=df.ffill()
df6

      name  subject      fee
0  Kuldeep     Math  10000.0
1    Rahul  English  10000.0
2    mohan  English   3839.0
3    Shyam    Hindi   3000.0
4     Aman  Science   3000.0

In [15]:
import pandas as pd
df=pd.read_csv("tested.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [16]:
df1=df.dropna()
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
...,...,...,...,...,...,...,...,...,...,...,...,...
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [18]:
df2=df.dropna(axis=1)
df2

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Embarked
0,892,0,3,"Kelly, Mr. James",male,0,0,330911,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,1,0,363272,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,0,0,240276,Q
3,895,0,3,"Wirz, Mr. Albert",male,0,0,315154,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,1,1,3101298,S
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,0,0,A.5. 3236,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,0,0,PC 17758,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,0,0,SOTON/O.Q. 3101262,S
416,1308,0,3,"Ware, Mr. Frederick",male,0,0,359309,S
417,1309,0,3,"Peter, Master. Michael J",male,1,1,2668,C

In [19]:
df3=df.fillna(39)
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,39,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,39,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,39,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,39,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,39,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,39.0,0,0,A.5. 3236,8.0500,39,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,39,S
416,1308,0,3,"Ware, Mr. Frederick",male,39.0,0,0,359309,8.0500,39,S
417,1309,0,3,"Peter, Master. Michael J",male,39.0,1,1,2668,22.3583,39,C

In [24]:
import pandas as pd
df=pd.DataFrame({"name":["Amit","rahul","soni","    mohan"]})
df

        name
0       Amit
1      rahul
2       soni
3      mohan

In [26]:
df["cap_name"]=df["name"].str.capitalize()
df

        name   cap_name
0       Amit       Amit
1      rahul      Rahul
2       soni       Soni
3      mohan      mohan

In [36]:
import pandas as pd
df=pd.DataFrame({"First_Name":["Amit","Shyam","Anjali","Rahul"],
                "Last_name":["sharma","prasad","Rai","pratap"]
})
df["Name"]=df["First_Name"]+" "+df["Last_name"]
print(df)

  First_Name Last_name          Name
0       Amit    sharma   Amit sharma
1      Shyam    prasad  Shyam prasad
2     Anjali       Rai    Anjali Rai
3      Rahul    pratap  Rahul pratap

In [38]:
df1=df["Name"].str.split(" ").str[1]
df1

0    sharma
1    prasad
2       Rai
3    pratap
Name: Name, dtype: object

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Email":[