1. Load the Excel file into a Pandas DataFrame.

In [375]:
import pandas as pd
df=pd.read_excel("D:\Messy_Inventory_Data.xlsx")
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,NaN,330.26,ABC Ltd,01/08/26,wh-a,Check stock
2,ITM1003,SSD,IT,176.0,1162.97,NaN,2026-08-01,wh-a,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,NaN,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,NaN,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,NaN,613.25,NaN,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,NaN,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,NaN,Printer,Networking,20.0,1437.85,NaN,2026-7-31,NaN,Check stock
8,ITM1009,SSD,Networking,34.0,618.06,ABC Ltd,2026/08/03,NaN,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,NaN,2026-7-31,WH-B,NaN
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,NaN,NaN
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,wh-a,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,NaN,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,NaN,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,NaN,NaN
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,SSD,IT,111.0,633.51,ABC Ltd,01/08/26,NaN,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,NaN,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,NaN,01/08/26,WH-A,NaN
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,wh-a,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,NaN,NaN
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,NaN,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,NaN,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,NaN
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,NaN,NaN
27,NaN,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,NaN,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaN,wh-a,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,wh-a,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,NaN,WH-A,Check stock
33,NaN,Printer,Networking,27.0,405.47,NaN,2026-08-01,wh-a,Check stock
34,ITM1035,SSD,Networking,NaN,520.72,TechCorp,2026-7-31,WH-B,NaN
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,wh-a,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,NaN,01/08/26,wh-a,Check stock
37,ITM1038,SSD,Furniture,36.0,1460.44,abc ltd,2026-08-01,wh-a,NaN
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,NaN
39,ITM1040,Chair,Furniture,116.0,26.30,NaN,2026-08-01,WH-B,NaN
40,ITM1041,cable,Furniture,60.0,731.97,abc ltd,2026/08/03,wh-a,Check stock
41,ITM1042,monitor,Networking,197.0,307.41,NaN,NaN,NaN,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,NaN,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,NaN,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,wh-a,Check stock
45,NaN,Router,Networking,102.0,1319.29,ABC Ltd,NaN,WH-A,Check stock
46,NaN,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,NaN
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,wh-a,NaN
48,ITM1049,printer,Networking,23.0,716.69,TechCorp,01/08/26,NaN,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,NaN,01/08/26,wh-a,Damaged
50,ITM1051,mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,NaN,Damaged
52,ITM1053,SSD,Furniture,NaN,1246.35,ABC Ltd,2026-7-31,wh-a,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,wh-a,NaN
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,NaN,NaN,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,NaN
58,ITM1059,Desk,IT,85.0,794.96,NaN,2026/08/03,NaN,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,wh-a,NaN

2. Display the first 10 records.

In [376]:
df.head(10)

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,NaN,330.26,ABC Ltd,01/08/26,wh-a,Check stock
2,ITM1003,SSD,IT,176.0,1162.97,NaN,2026-08-01,wh-a,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,NaN,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,NaN,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,NaN,613.25,NaN,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,NaN,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,NaN,Printer,Networking,20.0,1437.85,NaN,2026-7-31,NaN,Check stock
8,ITM1009,SSD,Networking,34.0,618.06,ABC Ltd,2026/08/03,NaN,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,NaN,2026-7-31,WH-B,NaN

3. Check the shape of the dataset.

In [377]:
print("Number of Rows: ",df.shape[0])
print("Number of Rows: ",df.shape[1])

Number of Rows:  60
Number of Rows:  9

4. Display column names and data types.

In [378]:
df.dtypes

Item ID             str
Item Name           str
Category            str
Qty             float64
Unit Price      float64
Supplier            str
Last Updated        str
Warehouse           str
Remarks             str
dtype: object

5. Find the total number of missing values in each column.

In [379]:
df.isnull().sum()

Item ID          5
Item Name        0
Category         0
Qty              5
Unit Price       0
Supplier        14
Last Updated     6
Warehouse       18
Remarks         16
dtype: int64

6. Replace all blank cells with 0 or None.

In [380]:
for col in df.columns:
    if df[col].dtype in ["int64","float64"]:
        df[col]=df[col].fillna(0)
    else:
        df[col]=df[col].fillna("None")
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,wh-a,Check stock
2,ITM1003,SSD,IT,176.0,1162.97,None,2026-08-01,wh-a,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,None,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,None,Check stock
8,ITM1009,SSD,Networking,34.0,618.06,ABC Ltd,2026/08/03,None,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,None,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,wh-a,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,None,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,None,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,SSD,IT,111.0,633.51,ABC Ltd,01/08/26,None,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,None,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,wh-a,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,None,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,None,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,None,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,None,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,wh-a,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,wh-a,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,wh-a,Check stock
34,ITM1035,SSD,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,wh-a,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,wh-a,Check stock
37,ITM1038,SSD,Furniture,36.0,1460.44,abc ltd,2026-08-01,wh-a,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,cable,Furniture,60.0,731.97,abc ltd,2026/08/03,wh-a,Check stock
41,ITM1042,monitor,Networking,197.0,307.41,None,None,None,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,None,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,wh-a,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,wh-a,None
48,ITM1049,printer,Networking,23.0,716.69,TechCorp,01/08/26,None,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,wh-a,Damaged
50,ITM1051,mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,None,Damaged
52,ITM1053,SSD,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,wh-a,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,wh-a,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,None,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,None,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,wh-a,None

7. Remove rows where the Item ID is missing.

In [381]:
df.dropna(subset=["Item ID"])

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,wh-a,Check stock
2,ITM1003,SSD,IT,176.0,1162.97,None,2026-08-01,wh-a,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,None,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,None,Check stock
8,ITM1009,SSD,Networking,34.0,618.06,ABC Ltd,2026/08/03,None,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,None,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,wh-a,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,None,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,None,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,SSD,IT,111.0,633.51,ABC Ltd,01/08/26,None,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,None,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,wh-a,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,None,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,None,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,None,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,None,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,wh-a,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,wh-a,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,wh-a,Check stock
34,ITM1035,SSD,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,wh-a,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,wh-a,Check stock
37,ITM1038,SSD,Furniture,36.0,1460.44,abc ltd,2026-08-01,wh-a,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,cable,Furniture,60.0,731.97,abc ltd,2026/08/03,wh-a,Check stock
41,ITM1042,monitor,Networking,197.0,307.41,None,None,None,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,None,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,wh-a,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,wh-a,None
48,ITM1049,printer,Networking,23.0,716.69,TechCorp,01/08/26,None,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,wh-a,Damaged
50,ITM1051,mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,None,Damaged
52,ITM1053,SSD,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,wh-a,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,wh-a,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,None,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,None,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,wh-a,None

8. Fill missing Supplier values with 'Unknown'.

In [382]:
df["Supplier"]=df["Supplier"].fillna("Unknown")
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,wh-a,Check stock
2,ITM1003,SSD,IT,176.0,1162.97,None,2026-08-01,wh-a,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,None,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,None,Check stock
8,ITM1009,SSD,Networking,34.0,618.06,ABC Ltd,2026/08/03,None,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,None,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,wh-a,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,None,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,None,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,SSD,IT,111.0,633.51,ABC Ltd,01/08/26,None,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,None,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,wh-a,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,None,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,None,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,None,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,None,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,wh-a,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,wh-a,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,wh-a,Check stock
34,ITM1035,SSD,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,wh-a,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,wh-a,Check stock
37,ITM1038,SSD,Furniture,36.0,1460.44,abc ltd,2026-08-01,wh-a,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,cable,Furniture,60.0,731.97,abc ltd,2026/08/03,wh-a,Check stock
41,ITM1042,monitor,Networking,197.0,307.41,None,None,None,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,None,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,wh-a,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,wh-a,None
48,ITM1049,printer,Networking,23.0,716.69,TechCorp,01/08/26,None,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,wh-a,Damaged
50,ITM1051,mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,None,Damaged
52,ITM1053,SSD,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,wh-a,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,wh-a,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,None,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,None,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,wh-a,None

9. Convert all Item Names to Title Case.

In [383]:
df["Item Name"]=df["Item Name"].str.title()
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,wh-a,Check stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-08-01,wh-a,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,None,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,None,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,2026/08/03,None,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,None,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,wh-a,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,None,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,None,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,01/08/26,None,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,None,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,wh-a,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,None,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,None,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,None,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,None,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,wh-a,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,wh-a,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,wh-a,Check stock
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,wh-a,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,wh-a,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-08-01,wh-a,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,2026/08/03,wh-a,Check stock
41,ITM1042,Monitor,Networking,197.0,307.41,None,None,None,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,None,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,wh-a,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,wh-a,None
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,01/08/26,None,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,wh-a,Damaged
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,None,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,wh-a,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,wh-a,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,None,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,None,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,wh-a,None

10. Convert all Warehouse names to uppercase.

In [384]:
df["Warehouse"]=df["Warehouse"].str.upper()
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,WH-A,Check stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-08-01,WH-A,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,NONE,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,NONE,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,2026/08/03,NONE,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,WH-A,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,NONE,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,NONE,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,01/08/26,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,NONE,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,WH-A,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,NONE,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,NONE,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,NONE,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,NONE,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,WH-A,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,WH-A,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,WH-A,Check stock
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,WH-A,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,WH-A,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-08-01,WH-A,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,2026/08/03,WH-A,Check stock
41,ITM1042,Monitor,Networking,197.0,307.41,None,None,NONE,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,NONE,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,WH-A,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,WH-A,None
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,01/08/26,NONE,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,WH-A,Damaged
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,NONE,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,WH-A,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,WH-A,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,NONE,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,NONE,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,WH-A,None

11. Remove leading and trailing spaces from every string column.

In [385]:
for col in df.select_dtypes(include="str").columns:
    df[col] = df[col].str.strip()
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,WH-A,Check stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-08-01,WH-A,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,NONE,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,NONE,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,2026/08/03,NONE,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,WH-A,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,NONE,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,NONE,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,01/08/26,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,NONE,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,WH-A,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,NONE,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,NONE,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,NONE,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,NONE,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,WH-A,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,WH-A,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,WH-A,Check stock
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,WH-A,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,WH-A,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-08-01,WH-A,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,2026/08/03,WH-A,Check stock
41,ITM1042,Monitor,Networking,197.0,307.41,None,None,NONE,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,NONE,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,WH-A,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,WH-A,None
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,01/08/26,NONE,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,WH-A,Damaged
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,NONE,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,WH-A,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,WH-A,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,NONE,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,NONE,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,WH-A,None

12. Identify duplicate records.

In [386]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

13. Remove duplicate records.

In [387]:
df.drop_duplicates()

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,WH-A,Check stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-08-01,WH-A,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,NONE,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,NONE,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,2026/08/03,NONE,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,WH-A,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,NONE,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,NONE,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,01/08/26,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,NONE,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,WH-A,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,NONE,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,NONE,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,NONE,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,NONE,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,WH-A,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,WH-A,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,WH-A,Check stock
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,WH-A,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,WH-A,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-08-01,WH-A,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,2026/08/03,WH-A,Check stock
41,ITM1042,Monitor,Networking,197.0,307.41,None,None,NONE,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,NONE,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,WH-A,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,WH-A,None
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,01/08/26,NONE,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,WH-A,Damaged
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,NONE,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,WH-A,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,WH-A,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,NONE,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,NONE,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,WH-A,None

14. Replace negative quantities with 0.

In [388]:
df.loc[df["Qty"] < 0, "Qty"] = 0
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-08-01,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,01/08/26,WH-A,Check stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-08-01,WH-A,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-08-01,NONE,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,01/08/26,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,2026-7-31,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,01/08/26,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,2026-7-31,NONE,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,2026/08/03,NONE,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,2026-7-31,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,2026-7-31,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,2026-7-31,WH-A,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,None,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,2026/08/03,NONE,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-08-01,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,01/08/26,NONE,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,01/08/26,WH-A,Check stock
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,01/08/26,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,2026-7-31,NONE,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,01/08/26,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,2026-7-31,WH-A,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,2026-7-31,NONE,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,01/08/26,NONE,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,2026-7-31,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,2026-7-31,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,2026/08/03,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-08-01,NONE,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-08-01,NONE,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,None,WH-A,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,2026-7-31,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-08-01,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,2026-7-31,WH-A,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,None,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-08-01,WH-A,Check stock
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,2026-7-31,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,2026-7-31,WH-A,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,01/08/26,WH-A,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-08-01,WH-A,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-08-01,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-08-01,WH-B,None
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,2026/08/03,WH-A,Check stock
41,ITM1042,Monitor,Networking,197.0,307.41,None,None,NONE,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,2026-7-31,NONE,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-08-01,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-08-01,WH-A,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,None,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,2026/08/03,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,01/08/26,WH-A,None
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,01/08/26,NONE,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,01/08/26,WH-A,Damaged
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,2026-7-31,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,2026/08/03,NONE,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,2026-7-31,WH-A,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,2026-7-31,WH-A,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,None,NONE,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,2026/08/03,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-08-01,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-08-01,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,2026/08/03,NONE,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,2026/08/03,WH-A,None

15. Convert the Last Updated column into datetime format.

In [390]:
df["Last Updated"] = pd.to_datetime(
    df["Last Updated"],
    errors="coerce",
    dayfirst=True
)

df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,NaT,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,NaT,NONE,None
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,NaT,NONE,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,NaT,NONE,None
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,NaT,WH-A,Check stock
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-01-08,WH-A,None
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,NaT,WH-A,Check stock
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,NaT,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,NaT,WH-A,None
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,NaT,WH-A,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,NaT,NONE,Damaged
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,NaT,WH-A,None

16. Display all products where Quantity is greater than 100.

In [391]:
df[df["Qty"] > 100]

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,NaT,NONE,duplicate?
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,NaT,WH-A,None
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,NaT,WH-A,None
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,NaT,WH-A,None
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,NaT,WH-A,None

17. Display products belonging to the IT category.

In [392]:
df[df["Category"] == "IT"]

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,NaT,NONE,duplicate?
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,NaT,WH-A,None
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,NaT,WH-A,None
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,NaT,NONE,Damaged
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock

18. Find products whose supplier is 'ABC Ltd'.

In [393]:
df[df["Supplier"] == "ABC Ltd"]

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?

19. Display records where Quantity is missing.

In [394]:
df[df["Qty"].isnull()]

Empty DataFrame
Columns: [Item ID, Item Name, Category, Qty, Unit Price, Supplier, Last Updated, Warehouse, Remarks]
Index: []

20. Find items having Unit Price greater than 1000.

In [395]:
df.loc[df["Unit Price"] >1000]

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,NaT,WH-A,Check stock
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,NaT,NONE,None
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-01-08,WH-A,None
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock
46,None,Monitor,Networking,152.0,1047.51,abc ltd,NaT,WH-A,None
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,NaT,NONE,Damaged
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged

21. Calculate the total inventory quantity.

In [396]:
print("Total inventory quantity")
df["Qty"].sum()

Total inventory quantity

np.float64(4973.0)

22. Find the average Unit Price.

In [397]:
print("Average unit Price")
df["Unit Price"].mean()

Average unit Price

np.float64(744.8348333333332)

23. Find the maximum quantity available.

In [398]:
print("Maximum quantity available")
max=df["Qty"].max()
print(max)

Maximum quantity available
197.0

24. Find the minimum Unit Price.

In [399]:
print("Minimum quantity available")
min=df["Qty"].min()
print(min)

Minimum quantity available
0.0

25. Create a new column 'Inventory Value = Qty × Unit Price'.

In [400]:
df["Inventory Value"]=df["Qty"]*df["Unit Price"]
df

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks,Inventory Value
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,NaT,WH-A,Check stock,11527.20
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,NaT,NONE,None,24669.12
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,NaT,NONE,duplicate?,40475.15
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,NaT,NONE,None,62739.00
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,NaT,WH-A,Check stock,11675.17
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-01-08,WH-A,None,52575.84
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,NaT,WH-A,Check stock,43918.20
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58
46,None,Monitor,Networking,152.0,1047.51,abc ltd,NaT,WH-A,None,159221.52
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,NaT,WH-A,None,106262.44
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,NaT,WH-A,None,82369.30
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,NaT,NONE,Damaged,77066.08
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,NaT,WH-A,None,77943.69

26. Find the total inventory value for each category.

In [401]:
df.groupby("Category")["Inventory Value"].sum()

Category
Furniture     1028746.96
IT            1161859.22
Networking    1385966.03
Name: Inventory Value, dtype: float64

27. Find the average quantity for each warehouse.

In [402]:
df["Warehouse"]=df["Warehouse"].str.upper()
df.groupby("Warehouse")["Qty"].mean()

Warehouse
NONE    83.555556
WH-A    78.161290
WH-B    95.090909
Name: Qty, dtype: float64

28. Find the supplier supplying the highest total inventory value.

In [403]:
print([df.groupby("Supplier")["Inventory Value"].sum().idxmax()])

['Global Inc']

29. Calculate the percentage contribution of each category to the total inventory value.

In [404]:
total=df.groupby("Category")["Inventory Value"].sum().sum()
print(total)
df.groupby("Category")["Inventory Value"].sum()/total*100

3576572.21

Category
Furniture     28.763489
IT            32.485272
Networking    38.751239
Name: Inventory Value, dtype: float64

30. Find the top 10 most expensive products.

In [405]:
df.sort_values(by="Qty", ascending=False).head(10)

,Item ID,Item Name,Category,Qty,Unit Price,Supplier,Last Updated,Warehouse,Remarks,Inventory Value
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,NaT,WH-A,None,106262.44
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65

31. Rename all columns using lowercase with underscores.

In [406]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74
12,ITM1013,Mouse,Networking,10.0,1152.72,abc ltd,NaT,WH-A,Check stock,11527.20
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98
15,ITM1016,Keyboard,Networking,32.0,770.91,abc ltd,NaT,NONE,None,24669.12
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61
18,ITM1019,Keyboard,IT,155.0,261.13,abc ltd,NaT,NONE,duplicate?,40475.15
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65
21,ITM1022,Laptop,Furniture,60.0,1045.65,abc ltd,NaT,NONE,None,62739.00
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51
32,ITM1033,Laptop,Furniture,13.0,898.09,abc ltd,NaT,WH-A,Check stock,11675.17
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96
37,ITM1038,Ssd,Furniture,36.0,1460.44,abc ltd,2026-01-08,WH-A,None,52575.84
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80
40,ITM1041,Cable,Furniture,60.0,731.97,abc ltd,NaT,WH-A,Check stock,43918.20
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58
46,None,Monitor,Networking,152.0,1047.51,abc ltd,NaT,WH-A,None,159221.52
47,ITM1048,Cable,IT,178.0,596.98,abc ltd,NaT,WH-A,None,106262.44
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00
53,ITM1054,Printer,IT,130.0,633.61,abc ltd,NaT,WH-A,None,82369.30
54,ITM1055,Desk,IT,52.0,1482.04,abc ltd,NaT,NONE,Damaged,77066.08
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60
59,ITM1060,Monitor,Networking,131.0,594.99,abc ltd,NaT,WH-A,None,77943.69

32. Replace 'abc ltd' with 'ABC Ltd'.

In [407]:
df["supplier"]=df["supplier"].str.replace("abc ltd","ABC Ltd")
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69

33. Find all rows where Quantity is 0.

In [408]:
df[df["qty"] == 0]

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.0
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.0
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.0
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.0
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.0

34. Sort the dataset by Unit Price in descending order.

In [409]:
df.sort_values(by="unit_price", ascending=False)

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80

35. Sort by Category and then Quantity.

In [410]:
df.sort_values(by=["category","qty"], ascending=False)

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00

36. Count the number of products in each category.

In [411]:
df.groupby("category")["item_name"].count()

category
Furniture     19
IT            16
Networking    25
Name: item_name, dtype: int64

37. Find the product with the highest inventory value.

In [412]:
df.loc[df["inventory_value"].idxmax()]

item_id                        ITM1003
item_name                          Ssd
category                            IT
qty                              176.0
unit_price                     1162.97
supplier                          None
last_updated       2026-01-08 00:00:00
warehouse                         WH-A
remarks                        Damaged
inventory_value              204682.72
Name: 2, dtype: object

38. Calculate the standard deviation of Unit Price.

In [413]:
std_unit_price = df["unit_price"].std()
print("standard deviation: ",std_unit_price)

standard deviation:  416.3177037991321

39. Calculate the median quantity.

In [414]:
median=df["qty"].median()
print("Median ",median)

Median  75.5

In [415]:
40. Generate descriptive statistics for all numerical columns.

SyntaxError: invalid syntax (314436260.py, line 1)

In [416]:
df.describe()

              qty   unit_price         last_updated  inventory_value
count   60.000000    60.000000                   15        60.000000
mean    82.883333   744.834833  2026-01-08 00:00:00     59609.536833
min      0.000000    26.300000  2026-01-08 00:00:00         0.000000
25%     26.000000   342.957500  2026-01-08 00:00:00     11382.322500
50%     75.500000   734.985000  2026-01-08 00:00:00     46923.490000
75%    130.250000  1087.065000  2026-01-08 00:00:00     84217.660000
max    197.000000  1487.920000  2026-01-08 00:00:00    204682.720000
std     62.130014   416.317704                  NaN     58191.260491

41. Create a Stock Status column (Out of Stock, Low, Medium, High).

In [417]:
def stock_status(qty):
    if qty == 0:
        return "Out of Stock"
    elif qty <= 50:
        return "Low"
    elif qty <= 100:
        return "Medium"
    else:
        return "High"

df["Stock Status"] = df["qty"].apply(stock_status)
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05,Low
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00,Out of Stock
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32,High
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95,Medium
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00,Out of Stock
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00,Out of Stock
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00,Low
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04,Low
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48,Medium
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74,Low
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20,Low
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44,Low
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12,Low
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20,Medium
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61,High
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15,High
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02,High
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65,High
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00,Medium
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75,Medium
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48,High
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40,High
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12,Medium
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51,Low
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66,Medium
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74,Low
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35,Medium
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40,Medium
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51,High
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17,Low
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69,Low
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00,Out of Stock
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85,High
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96,High
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84,Low
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12,Low
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80,High
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20,Medium
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77,High
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78,High
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65,Medium
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58,High
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52,High
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44,High
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87,Low
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88,Low
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68,Low
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29,High
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00,Out of Stock
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30,High
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08,Medium
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74,Medium
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00,High
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60,Medium
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69,High

42. Create a 10% discounted price column.

In [418]:
df["Discount_10%"]=df["unit_price"]*.1
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status,Discount_10%
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05,Low,82.885
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00,Out of Stock,33.026
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High,116.297
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32,High,59.968
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95,Medium,26.063
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00,Out of Stock,61.325
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00,Out of Stock,29.106
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00,Low,143.785
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04,Low,61.806
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High,107.617
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48,Medium,108.864
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74,Low,120.646
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20,Low,115.272
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44,Low,141.074
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High,123.819
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12,Low,77.091
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20,Medium,30.430
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61,High,63.351
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15,High,26.113
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02,High,18.039
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65,High,74.735
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00,Medium,104.565
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75,Medium,13.825
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48,High,33.848
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40,High,5.560
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12,Medium,108.256
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51,Low,118.257
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66,Medium,113.267
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74,Low,82.437
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35,Medium,32.195
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40,Medium,74.895
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51,High,96.241
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17,Low,89.809
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69,Low,40.547
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00,Out of Stock,52.072
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85,High,5.097
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96,High,148.792
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84,Low,146.044
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12,Low,50.689
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80,High,2.630
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20,Medium,73.197
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77,High,30.741
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High,108.654
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78,High,39.314
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65,Medium,34.445
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58,High,131.929
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52,High,104.751
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44,High,59.698
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87,Low,71.669
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88,Low,21.397
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68,Low,16.171
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29,High,72.439
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00,Out of Stock,124.635
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30,High,63.361
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08,Medium,148.204
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High,93.970
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74,Medium,121.301
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00,High,73.800
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60,Medium,79.496
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69,High,59.499

43. Create a GST (18%) column.

In [419]:
df["GST_18%"]=df["unit_price"]*.18
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status,Discount_10%,GST_18%
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05,Low,82.885,149.1930
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00,Out of Stock,33.026,59.4468
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High,116.297,209.3346
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32,High,59.968,107.9424
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95,Medium,26.063,46.9134
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00,Out of Stock,61.325,110.3850
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00,Out of Stock,29.106,52.3908
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00,Low,143.785,258.8130
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04,Low,61.806,111.2508
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High,107.617,193.7106
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48,Medium,108.864,195.9552
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74,Low,120.646,217.1628
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20,Low,115.272,207.4896
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44,Low,141.074,253.9332
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High,123.819,222.8742
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12,Low,77.091,138.7638
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20,Medium,30.430,54.7740
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61,High,63.351,114.0318
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15,High,26.113,47.0034
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02,High,18.039,32.4702
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65,High,74.735,134.5230
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00,Medium,104.565,188.2170
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75,Medium,13.825,24.8850
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48,High,33.848,60.9264
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40,High,5.560,10.0080
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12,Medium,108.256,194.8608
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51,Low,118.257,212.8626
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66,Medium,113.267,203.8806
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74,Low,82.437,148.3866
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35,Medium,32.195,57.9510
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40,Medium,74.895,134.8110
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51,High,96.241,173.2338
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17,Low,89.809,161.6562
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69,Low,40.547,72.9846
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00,Out of Stock,52.072,93.7296
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85,High,5.097,9.1746
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96,High,148.792,267.8256
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84,Low,146.044,262.8792
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12,Low,50.689,91.2402
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80,High,2.630,4.7340
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20,Medium,73.197,131.7546
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77,High,30.741,55.3338
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High,108.654,195.5772
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78,High,39.314,70.7652
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65,Medium,34.445,62.0010
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58,High,131.929,237.4722
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52,High,104.751,188.5518
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44,High,59.698,107.4564
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87,Low,71.669,129.0042
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88,Low,21.397,38.5146
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68,Low,16.171,29.1078
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29,High,72.439,130.3902
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00,Out of Stock,124.635,224.3430
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30,High,63.361,114.0498
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08,Medium,148.204,266.7672
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High,93.970,169.1460
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74,Medium,121.301,218.3418
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00,High,73.800,132.8400
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60,Medium,79.496,143.0928
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69,High,59.499,107.0982

44. Calculate the final selling price after GST.

In [420]:
df["Selling price"]=df["unit_price"]+df["GST_18%"]-df["Discount_10%"]
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status,Discount_10%,GST_18%,Selling price
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05,Low,82.885,149.1930,895.1580
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00,Out of Stock,33.026,59.4468,356.6808
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High,116.297,209.3346,1256.0076
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32,High,59.968,107.9424,647.6544
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95,Medium,26.063,46.9134,281.4804
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00,Out of Stock,61.325,110.3850,662.3100
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00,Out of Stock,29.106,52.3908,314.3448
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00,Low,143.785,258.8130,1552.8780
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04,Low,61.806,111.2508,667.5048
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High,107.617,193.7106,1162.2636
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48,Medium,108.864,195.9552,1175.7312
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74,Low,120.646,217.1628,1302.9768
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20,Low,115.272,207.4896,1244.9376
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44,Low,141.074,253.9332,1523.5992
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High,123.819,222.8742,1337.2452
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12,Low,77.091,138.7638,832.5828
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20,Medium,30.430,54.7740,328.6440
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61,High,63.351,114.0318,684.1908
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15,High,26.113,47.0034,282.0204
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02,High,18.039,32.4702,194.8212
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65,High,74.735,134.5230,807.1380
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00,Medium,104.565,188.2170,1129.3020
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75,Medium,13.825,24.8850,149.3100
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48,High,33.848,60.9264,365.5584
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40,High,5.560,10.0080,60.0480
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12,Medium,108.256,194.8608,1169.1648
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51,Low,118.257,212.8626,1277.1756
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66,Medium,113.267,203.8806,1223.2836
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74,Low,82.437,148.3866,890.3196
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35,Medium,32.195,57.9510,347.7060
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40,Medium,74.895,134.8110,808.8660
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51,High,96.241,173.2338,1039.4028
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17,Low,89.809,161.6562,969.9372
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69,Low,40.547,72.9846,437.9076
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00,Out of Stock,52.072,93.7296,562.3776
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85,High,5.097,9.1746,55.0476
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96,High,148.792,267.8256,1606.9536
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84,Low,146.044,262.8792,1577.2752
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12,Low,50.689,91.2402,547.4412
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80,High,2.630,4.7340,28.4040
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20,Medium,73.197,131.7546,790.5276
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77,High,30.741,55.3338,332.0028
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High,108.654,195.5772,1173.4632
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78,High,39.314,70.7652,424.5912
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65,Medium,34.445,62.0010,372.0060
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58,High,131.929,237.4722,1424.8332
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52,High,104.751,188.5518,1131.3108
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44,High,59.698,107.4564,644.7384
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87,Low,71.669,129.0042,774.0252
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88,Low,21.397,38.5146,231.0876
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68,Low,16.171,29.1078,174.6468
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29,High,72.439,130.3902,782.3412
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00,Out of Stock,124.635,224.3430,1346.0580
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30,High,63.361,114.0498,684.2988
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08,Medium,148.204,266.7672,1600.6032
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High,93.970,169.1460,1014.8760
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74,Medium,121.301,218.3418,1310.0508
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00,High,73.800,132.8400,797.0400
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60,Medium,79.496,143.0928,858.5568
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69,High,59.499,107.0982,642.5892

45. Find products having inventory value greater than ₹50,000.

In [421]:
df[df["inventory_value"]>50000]

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status,Discount_10%,GST_18%,Selling price
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High,116.297,209.3346,1256.0076
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32,High,59.968,107.9424,647.6544
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High,107.617,193.7106,1162.2636
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48,Medium,108.864,195.9552,1175.7312
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High,123.819,222.8742,1337.2452
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61,High,63.351,114.0318,684.1908
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65,High,74.735,134.5230,807.1380
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00,Medium,104.565,188.2170,1129.3020
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48,High,33.848,60.9264,365.5584
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12,Medium,108.256,194.8608,1169.1648
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51,Low,118.257,212.8626,1277.1756
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66,Medium,113.267,203.8806,1223.2836
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40,Medium,74.895,134.8110,808.8660
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51,High,96.241,173.2338,1039.4028
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96,High,148.792,267.8256,1606.9536
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84,Low,146.044,262.8792,1577.2752
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77,High,30.741,55.3338,332.0028
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High,108.654,195.5772,1173.4632
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58,High,131.929,237.4722,1424.8332
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52,High,104.751,188.5518,1131.3108
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44,High,59.698,107.4564,644.7384
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29,High,72.439,130.3902,782.3412
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30,High,63.361,114.0498,684.2988
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08,Medium,148.204,266.7672,1600.6032
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High,93.970,169.1460,1014.8760
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74,Medium,121.301,218.3418,1310.0508
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00,High,73.800,132.8400,797.0400
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60,Medium,79.496,143.0928,858.5568
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69,High,59.499,107.0982,642.5892

46. Find the top 5 suppliers by inventory value.

In [422]:
print(df.sort_values(by="inventory_value",ascending=False)["supplier"].head(5))
df.sort_values(by="inventory_value",ascending=False).head(5)

2           None
42    Global Inc
9           None
14    Global Inc
55      TechCorp
Name: supplier, dtype: str

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status,Discount_10%,GST_18%,Selling price
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High,116.297,209.3346,1256.0076
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High,108.654,195.5772,1173.4632
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High,107.617,193.7106,1162.2636
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High,123.819,222.8742,1337.2452
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High,93.970,169.1460,1014.8760

47. Find the percentage of missing data in every column.

In [423]:
(df.isnull().sum() / len(df)) * 100

item_id             0.0
item_name           0.0
category            0.0
qty                 0.0
unit_price          0.0
supplier            0.0
last_updated       75.0
warehouse           0.0
remarks             0.0
inventory_value     0.0
Stock Status        0.0
Discount_10%        0.0
GST_18%             0.0
Selling price       0.0
dtype: float64

48. Remove rows where more than three columns contain missing values.

In [424]:
df = df[df.isnull().sum(axis=1) <= 3]
df

,item_id,item_name,category,qty,unit_price,supplier,last_updated,warehouse,remarks,inventory_value,Stock Status,Discount_10%,GST_18%,Selling price
0,ITM1001,Cable,IT,33.0,828.85,ABC Ltd,2026-01-08,WH-A,Damaged,27352.05,Low,82.885,149.1930,895.1580
1,ITM1002,Router,Networking,0.0,330.26,ABC Ltd,NaT,WH-A,Check stock,0.00,Out of Stock,33.026,59.4468,356.6808
2,ITM1003,Ssd,IT,176.0,1162.97,None,2026-01-08,WH-A,Damaged,204682.72,High,116.297,209.3346,1256.0076
3,ITM1004,Laptop,Networking,174.0,599.68,Global Inc,2026-01-08,NONE,Damaged,104344.32,High,59.968,107.9424,647.6544
4,ITM1005,Keyboard,Networking,65.0,260.63,None,NaT,WH-A,duplicate?,16940.95,Medium,26.063,46.9134,281.4804
5,ITM1006,Mouse,IT,0.0,613.25,None,NaT,WH-A,Check stock,0.00,Out of Stock,61.325,110.3850,662.3100
6,ITM1007,Desk,Furniture,0.0,291.06,ABC Ltd,NaT,WH-B,Check stock,0.00,Out of Stock,29.106,52.3908,314.3448
7,None,Printer,Networking,20.0,1437.85,None,NaT,NONE,Check stock,28757.00,Low,143.785,258.8130,1552.8780
8,ITM1009,Ssd,Networking,34.0,618.06,ABC Ltd,NaT,NONE,duplicate?,21014.04,Low,61.806,111.2508,667.5048
9,ITM1010,Chair,Furniture,178.0,1076.17,None,NaT,WH-B,None,191558.26,High,107.617,193.7106,1162.2636
10,ITM1011,Chair,Furniture,57.0,1088.64,ABC Ltd,NaT,NONE,None,62052.48,Medium,108.864,195.9552,1175.7312
11,ITM1012,Laptop,Networking,19.0,1206.46,ABC Ltd,NaT,WH-A,Damaged,22922.74,Low,120.646,217.1628,1302.9768
12,ITM1013,Mouse,Networking,10.0,1152.72,ABC Ltd,NaT,WH-A,Check stock,11527.20,Low,115.272,207.4896,1244.9376
13,ITM1014,Printer,Furniture,6.0,1410.74,Global Inc,NaT,NONE,duplicate?,8464.44,Low,141.074,253.9332,1523.5992
14,ITM1015,Mouse,IT,142.0,1238.19,Global Inc,2026-01-08,WH-B,duplicate?,175822.98,High,123.819,222.8742,1337.2452
15,ITM1016,Keyboard,Networking,32.0,770.91,ABC Ltd,NaT,NONE,None,24669.12,Low,77.091,138.7638,832.5828
16,ITM1017,Router,Furniture,74.0,304.30,Global Inc,NaT,WH-A,Check stock,22518.20,Medium,30.430,54.7740,328.6440
17,ITM1018,Ssd,IT,111.0,633.51,ABC Ltd,NaT,NONE,Damaged,70319.61,High,63.351,114.0318,684.1908
18,ITM1019,Keyboard,IT,155.0,261.13,ABC Ltd,NaT,NONE,duplicate?,40475.15,High,26.113,47.0034,282.0204
19,ITM1020,Printer,Networking,118.0,180.39,None,NaT,WH-A,None,21286.02,High,18.039,32.4702,194.8212
20,ITM1021,Printer,Networking,159.0,747.35,ABC Ltd,NaT,WH-A,Check stock,118828.65,High,74.735,134.5230,807.1380
21,ITM1022,Laptop,Furniture,60.0,1045.65,ABC Ltd,NaT,NONE,None,62739.00,Medium,104.565,188.2170,1129.3020
22,ITM1023,Router,Furniture,67.0,138.25,Global Inc,NaT,NONE,duplicate?,9262.75,Medium,13.825,24.8850,149.3100
23,ITM1024,Monitor,Furniture,176.0,338.48,ABC Ltd,NaT,WH-A,duplicate?,59572.48,High,33.848,60.9264,365.5584
24,ITM1025,Desk,Networking,134.0,55.60,None,NaT,WH-A,Damaged,7450.40,High,5.560,10.0080,60.0480
25,ITM1026,Keyboard,Furniture,52.0,1082.56,TechCorp,NaT,WH-A,None,56293.12,Medium,108.256,194.8608,1169.1648
26,ITM1027,Mouse,Furniture,43.0,1182.57,ABC Ltd,2026-01-08,NONE,None,50850.51,Low,118.257,212.8626,1277.1756
27,None,Cable,IT,98.0,1132.67,TechCorp,2026-01-08,NONE,Check stock,111001.66,Medium,113.267,203.8806,1223.2836
28,ITM1029,Mouse,Furniture,2.0,824.37,ABC Ltd,NaT,WH-A,Damaged,1648.74,Low,82.437,148.3866,890.3196
29,ITM1030,Monitor,Furniture,93.0,321.95,ABC Ltd,NaT,WH-B,duplicate?,29941.35,Medium,32.195,57.9510,347.7060
30,ITM1031,Mouse,Networking,92.0,748.95,ABC Ltd,2026-01-08,WH-A,duplicate?,68903.40,Medium,74.895,134.8110,808.8660
31,ITM1032,Chair,Networking,111.0,962.41,Global Inc,NaT,WH-A,Damaged,106827.51,High,96.241,173.2338,1039.4028
32,ITM1033,Laptop,Furniture,13.0,898.09,ABC Ltd,NaT,WH-A,Check stock,11675.17,Low,89.809,161.6562,969.9372
33,None,Printer,Networking,27.0,405.47,None,2026-01-08,WH-A,Check stock,10947.69,Low,40.547,72.9846,437.9076
34,ITM1035,Ssd,Networking,0.0,520.72,TechCorp,NaT,WH-B,None,0.00,Out of Stock,52.072,93.7296,562.3776
35,ITM1036,Printer,IT,105.0,50.97,Global Inc,NaT,WH-A,Damaged,5351.85,High,5.097,9.1746,55.0476
36,ITM1037,Keyboard,Furniture,113.0,1487.92,None,NaT,WH-A,Check stock,168134.96,High,148.792,267.8256,1606.9536
37,ITM1038,Ssd,Furniture,36.0,1460.44,ABC Ltd,2026-01-08,WH-A,None,52575.84,Low,146.044,262.8792,1577.2752
38,ITM1039,Laptop,IT,8.0,506.89,TechCorp,2026-01-08,WH-B,None,4055.12,Low,50.689,91.2402,547.4412
39,ITM1040,Chair,Furniture,116.0,26.30,None,2026-01-08,WH-B,None,3050.80,High,2.630,4.7340,28.4040
40,ITM1041,Cable,Furniture,60.0,731.97,ABC Ltd,NaT,WH-A,Check stock,43918.20,Medium,73.197,131.7546,790.5276
41,ITM1042,Monitor,Networking,197.0,307.41,None,NaT,NONE,duplicate?,60559.77,High,30.741,55.3338,332.0028
42,ITM1043,Router,Furniture,179.0,1086.54,Global Inc,NaT,NONE,duplicate?,194490.66,High,108.654,195.5772,1173.4632
43,ITM1044,Cable,IT,127.0,393.14,None,2026-01-08,WH-B,Check stock,49928.78,High,39.314,70.7652,424.5912
44,ITM1045,Chair,Networking,77.0,344.45,Global Inc,2026-01-08,WH-A,Check stock,26522.65,Medium,34.445,62.0010,372.0060
45,None,Router,Networking,102.0,1319.29,ABC Ltd,NaT,WH-A,Check stock,134567.58,High,131.929,237.4722,1424.8332
46,None,Monitor,Networking,152.0,1047.51,ABC Ltd,NaT,WH-A,None,159221.52,High,104.751,188.5518,1131.3108
47,ITM1048,Cable,IT,178.0,596.98,ABC Ltd,NaT,WH-A,None,106262.44,High,59.698,107.4564,644.7384
48,ITM1049,Printer,Networking,23.0,716.69,TechCorp,NaT,NONE,Check stock,16483.87,Low,71.669,129.0042,774.0252
49,ITM1050,Keyboard,IT,4.0,213.97,None,NaT,WH-A,Damaged,855.88,Low,21.397,38.5146,231.0876
50,ITM1051,Mouse,Networking,8.0,161.71,TechCorp,NaT,WH-B,duplicate?,1293.68,Low,16.171,29.1078,174.6468
51,ITM1052,Laptop,Networking,111.0,724.39,ABC Ltd,NaT,NONE,Damaged,80407.29,High,72.439,130.3902,782.3412
52,ITM1053,Ssd,Furniture,0.0,1246.35,ABC Ltd,NaT,WH-A,duplicate?,0.00,Out of Stock,124.635,224.3430,1346.0580
53,ITM1054,Printer,IT,130.0,633.61,ABC Ltd,NaT,WH-A,None,82369.30,High,63.361,114.0498,684.2988
54,ITM1055,Desk,IT,52.0,1482.04,ABC Ltd,NaT,NONE,Damaged,77066.08,Medium,148.204,266.7672,1600.6032
55,ITM1056,Desk,Networking,186.0,939.70,TechCorp,NaT,WH-B,Check stock,174784.20,High,93.970,169.1460,1014.8760
56,ITM1057,Laptop,Networking,74.0,1213.01,Global Inc,2026-01-08,WH-A,Damaged,89762.74,Medium,121.301,218.3418,1310.0508
57,ITM1058,Mouse,IT,188.0,738.00,Global Inc,2026-01-08,WH-B,None,138744.00,High,73.800,132.8400,797.0400
58,ITM1059,Desk,IT,85.0,794.96,None,NaT,NONE,Check stock,67571.60,Medium,79.496,143.0928,858.5568
59,ITM1060,Monitor,Networking,131.0,594.99,ABC Ltd,NaT,WH-A,None,77943.69,High,59.499,107.0982,642.5892

49. Export the cleaned dataset to Cleaned_Inventory.xlsx.

In [425]:
df.to_excel(r'C:\Users\KULDEEP SHARMA\OneDrive\Desktop\shivani\Clened_Inventory.xlsx',index=False,header=True)

50. Create a summary report with totals, averages, highest/lowest priced products, categories, and suppliers.

In [428]:
summary = {
    "Total Products": len(df),
    "Total Inventory Quantity": df["qty"].sum(),
    "Average Unit Price": df["unit_price"].mean(),
    "Highest Priced Product": df.loc[df["unit_price"].idxmax(), "item_name"],
    "Highest Price": df["unit_price"].max(),
    "Lowest Priced Product": df.loc[df["unit_price"].idxmin(), "item_name"],
    "Lowest Price": df["unit_price"].min(),
    "Total Categories": df["category"].nunique(),
    "Categories": df["category"].unique().tolist(),
    "Total Suppliers": df["supplier"].nunique(),
    "Suppliers": df["supplier"].dropna().unique().tolist()
}

for key, value in summary.items():
    print(f"{key}: {value}")

Total Products: 60
Total Inventory Quantity: 4973.0
Average Unit Price: 744.8348333333332
Highest Priced Product: Keyboard
Highest Price: 1487.92
Lowest Priced Product: Chair
Lowest Price: 26.3
Total Categories: 3
Categories: ['IT', 'Networking', 'Furniture']
Total Suppliers: 4
Suppliers: ['ABC Ltd', 'None', 'Global Inc', 'TechCorp']