In [38]:
import pandas as pd
data={"Name":["Riya","Rohan","Seema","Neha"],"Age":[23,43,12,32],"Salary":[20000,30000,40000,50000]}
df=pd.DataFrame(data,index=[1.1,1.2,1.3,1.4],columns=["Name","Salary","Age"])
print(df)

      Name  Salary  Age
1.1   Riya   20000   23
1.2  Rohan   30000   43
1.3  Seema   40000   12
1.4   Neha   50000   32

In [13]:
df.head(2)

      Name  Salary  Age
1.1   Riya   20000   23
1.2  Rohan   30000   43

In [14]:
df.tail(1)

     Name  Salary  Age
1.4  Neha   50000   32

In [39]:
Name=["Ram","shyam","Mohan","smary"]
Age=[23,43,43,12]
Salary=[30000,20000,40000,30292]
data=zip(Name,Age,Salary)
df=pd.DataFrame(data,columns=["Name","Age","Salary"])
df

    Name  Age  Salary
0    Ram   23   30000
1  shyam   43   20000
2  Mohan   43   40000
3  smary   12   30292

In [77]:
df=pd.read_csv("MegaMart.csv")
df

,order_id,user_id,order_date,product_id,product_category,product_name,quantity,price_per_unit,payment_method,order_status
0,1001,U188,2025-04-20,P940,Fashion,Sneakers,2,58.53,PayPal,Cancelled
1,1002,U062,2025-04-16,P794,Fashion,T-Shirt,3,83.76,UPI,Returned
2,1003,U058,2025-04-18,P326,Fashion,Sunglasses,2,78.85,PayPal,Processing
3,1004,U011,2025-04-10,P574,Fashion,Sunglasses,5,46.49,PayPal,Delivered
4,1005,U003,2025-04-19,P988,Home Decor,Photo Frame,2,78.61,PayPal,Returned
...,...,...,...,...,...,...,...,...,...,...
995,1996,U039,2025-04-16,P860,Kitchen,Microwave,1,51.10,Debit Card,Processing
996,1997,U132,2025-04-18,P126,Fashion,T-Shirt,5,98.35,Credit Card,Processing
997,1998,U193,2025-04-17,P651,Books,Clean Code,1,28.02,Credit Card,Processing
998,1999,U150,2025-04-22,P900,Kitchen,Toaster,2,33.72,PayPal,Cancelled
999,2000,U010,2025-04-18,P870,Kitchen,Toaster,3,84.03,Debit Card,Cancelled

In [78]:
df1=pd.DataFrame(df,columns=["product_name","quantity","price_per_unit"])
df1

    product_name  quantity  price_per_unit
0       Sneakers         2           58.53
1        T-Shirt         3           83.76
2     Sunglasses         2           78.85
3     Sunglasses         5           46.49
4    Photo Frame         2           78.61
..           ...       ...             ...
995    Microwave         1           51.10
996      T-Shirt         5           98.35
997   Clean Code         1           28.02
998      Toaster         2           33.72
999      Toaster         3           84.03

[1000 rows x 3 columns]

In [79]:
df2=df1.head(20)
df2

            product_name  quantity  price_per_unit
0               Sneakers         2           58.53
1                T-Shirt         3           83.76
2             Sunglasses         2           78.85
3             Sunglasses         5           46.49
4            Photo Frame         2           78.61
5              Knife Set         4           53.51
6             Wall Clock         5           12.71
7            Photo Frame         1           46.60
8                Toaster         4           35.87
9              Microwave         1           30.95
10           USB-C Cable         4           18.79
11            Sunglasses         5           69.14
12              Sneakers         5           90.64
13  Data Engineering 101         1           93.91
14            Sunglasses         1           61.00
15            Smartwatch         2           54.77
16    Big Data Explained         5           13.42
17        Wireless Mouse         2           18.72
18               Blender         3           35.68
19               Blender         4           56.08

In [80]:
df2["Total"]=df2["quantity"]*df2["price_per_unit"]
df2

            product_name  quantity  price_per_unit   Total
0               Sneakers         2           58.53  117.06
1                T-Shirt         3           83.76  251.28
2             Sunglasses         2           78.85  157.70
3             Sunglasses         5           46.49  232.45
4            Photo Frame         2           78.61  157.22
5              Knife Set         4           53.51  214.04
6             Wall Clock         5           12.71   63.55
7            Photo Frame         1           46.60   46.60
8                Toaster         4           35.87  143.48
9              Microwave         1           30.95   30.95
10           USB-C Cable         4           18.79   75.16
11            Sunglasses         5           69.14  345.70
12              Sneakers         5           90.64  453.20
13  Data Engineering 101         1           93.91   93.91
14            Sunglasses         1           61.00   61.00
15            Smartwatch         2           54.77  109.54
16    Big Data Explained         5           13.42   67.10
17        Wireless Mouse         2           18.72   37.44
18               Blender         3           35.68  107.04
19               Blender         4           56.08  224.32

In [81]:
df2["GST"]=df2["Total"]*.1
df2

            product_name  quantity  price_per_unit   Total     GST
0               Sneakers         2           58.53  117.06  11.706
1                T-Shirt         3           83.76  251.28  25.128
2             Sunglasses         2           78.85  157.70  15.770
3             Sunglasses         5           46.49  232.45  23.245
4            Photo Frame         2           78.61  157.22  15.722
5              Knife Set         4           53.51  214.04  21.404
6             Wall Clock         5           12.71   63.55   6.355
7            Photo Frame         1           46.60   46.60   4.660
8                Toaster         4           35.87  143.48  14.348
9              Microwave         1           30.95   30.95   3.095
10           USB-C Cable         4           18.79   75.16   7.516
11            Sunglasses         5           69.14  345.70  34.570
12              Sneakers         5           90.64  453.20  45.320
13  Data Engineering 101         1           93.91   93.91   9.391
14            Sunglasses         1           61.00   61.00   6.100
15            Smartwatch         2           54.77  109.54  10.954
16    Big Data Explained         5           13.42   67.10   6.710
17        Wireless Mouse         2           18.72   37.44   3.744
18               Blender         3           35.68  107.04  10.704
19               Blender         4           56.08  224.32  22.432

In [82]:
df2["Gross total"]=df2["Total"]+df2["GST"]
df2

,product_name,quantity,price_per_unit,Total,GST,Gross total
0,Sneakers,2,58.53,117.06,11.706,128.766
1,T-Shirt,3,83.76,251.28,25.128,276.408
2,Sunglasses,2,78.85,157.70,15.770,173.470
3,Sunglasses,5,46.49,232.45,23.245,255.695
4,Photo Frame,2,78.61,157.22,15.722,172.942
5,Knife Set,4,53.51,214.04,21.404,235.444
6,Wall Clock,5,12.71,63.55,6.355,69.905
7,Photo Frame,1,46.60,46.60,4.660,51.260
8,Toaster,4,35.87,143.48,14.348,157.828
9,Microwave,1,30.95,30.95,3.095,34.045
10,USB-C Cable,4,18.79,75.16,7.516,82.676
11,Sunglasses,5,69.14,345.70,34.570,380.270
12,Sneakers,5,90.64,453.20,45.320,498.520
13,Data Engineering 101,1,93.91,93.91,9.391,103.301
14,Sunglasses,1,61.00,61.00,6.100,67.100
15,Smartwatch,2,54.77,109.54,10.954,120.494
16,Big Data Explained,5,13.42,67.10,6.710,73.810
17,Wireless Mouse,2,18.72,37.44,3.744,41.184
18,Blender,3,35.68,107.04,10.704,117.744
19,Blender,4,56.08,224.32,22.432,246.752

In [83]:
df3=df2.groupby("product_name")["quantity"].sum()
df3

product_name
Big Data Explained       5
Blender                  7
Data Engineering 101     1
Knife Set                4
Microwave                1
Photo Frame              3
Smartwatch               2
Sneakers                 7
Sunglasses              13
T-Shirt                  3
Toaster                  4
USB-C Cable              4
Wall Clock               5
Wireless Mouse           2
Name: quantity, dtype: int64

In [84]:
df4=df2.groupby("product_name")["quantity"].mean()
df4

product_name
Big Data Explained      5.00
Blender                 3.50
Data Engineering 101    1.00
Knife Set               4.00
Microwave               1.00
Photo Frame             1.50
Smartwatch              2.00
Sneakers                3.50
Sunglasses              3.25
T-Shirt                 3.00
Toaster                 4.00
USB-C Cable             4.00
Wall Clock              5.00
Wireless Mouse          2.00
Name: quantity, dtype: float64

In [91]:
import pandas as pd 
data={"Branch":["A","B","C"],
      "State":["Delhi","Mumbai","Kolkata"],
      "Amount":[100,250,150]
     }
df=pd.DataFrame(data)
print(df)

  Branch    State  Amount
0      A    Delhi     100
1      B   Mumbai     250
2      C  Kolkata     150

In [86]:
df.loc[2]

Branch          C
State     Kolkata
Amount        150
Name: 2, dtype: object

In [88]:
df.loc[1,"State"]

'Mumbai'

In [89]:
df.iloc[1]

Branch         B
State     Mumbai
Amount       250
Name: 1, dtype: object

In [94]:
i=df["Amount"].idxmax()
print(i)

1

In [111]:
import pandas as pd
df=pd.read_excel("D:\CSV file reading\BlinkIT Grocery Data (1).xlsx",sheet_name='BlinkIT Grocery Data')
df

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,low fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,164.5526,4.0
8519,low fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,NaN,241.6828,4.0
8520,low fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,NaN,86.6198,4.0
8521,reg,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,NaN,97.8752,4.0
8522,reg,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,112.2544,4.0

In [112]:
i=df["Sales"].idxmax()
df.loc[i]

Item Fat Content                       Low Fat
Item Identifier                          FDS13
Item Type                               Canned
Outlet Establishment Year                 2020
Outlet Identifier                       OUT017
Outlet Location Type                    Tier 2
Outlet Size                              Small
Outlet Type                  Supermarket Type1
Item Visibility                        0.12521
Item Weight                              6.465
Sales                                 266.8884
Rating                                     5.0
Name: 183, dtype: object

In [113]:
import pandas as pd
data={'Student':['Alice','Riya','Aman','Hari'],
      'Class':['9A','6C','9A','6C'],
      'English':[84,78,70,81],
      'Science':[56,78,90,67]}
df=pd.DataFrame(data)
print(df)

  Student Class  English  Science
0   Alice    9A       84       56
1    Riya    6C       78       78
2    Aman    9A       70       90
3    Hari    6C       81       67

In [115]:
df.loc[1:2,"English"]

1    78
2    70
Name: English, dtype: int64

In [117]:
df1=(df.loc[0:3,"English"]>80).idxmax()
df1

0

In [119]:
df1.loc[index_max,"Student"]

AttributeError: 'int' object has no attribute 'loc'

In [120]:
import pandas as pd

data={'Student':['Alice','Riya','Aman','Hari'],
      'Class':['9A','6C','9A','6C'],
      'English':[84,78,70,81],
      'Science':[56,78,90,67]}
df=pd.DataFrame(data)

print("Original DataFrame:\n", df, "\n")

# 1. Sort by English marks (descending)
df_sorted = df.sort_values(by="English", ascending=False)
print("Sorted by English (descending):\n", df_sorted, "\n")

# 2. Drop the 'Class' column
df_dropped = df.drop(columns=['Class'])
print("After dropping 'Class' column:\n", df_dropped, "\n")

# 3. Rename column 'Science' → 'Science_Marks'
df_renamed = df.rename(columns={'Science': 'Science_Marks'})
print("After renaming column:\n", df_renamed, "\n")

# 4. Remove duplicates (if any)
df_no_duplicates = df.drop_duplicates()
print("After dropping duplicates:\n", df_no_duplicates, "\n")

# 5. Reset index after sorting
df_reset = df_sorted.reset_index(drop=True)
print("After resetting index:\n", df_reset)

Original DataFrame:
   Student Class  English  Science
0   Alice    9A       84       56
1    Riya    6C       78       78
2    Aman    9A       70       90
3    Hari    6C       81       67

Sorted by English (descending):
   Student Class  English  Science
0   Alice    9A       84       56
3    Hari    6C       81       67
1    Riya    6C       78       78
2    Aman    9A       70       90

After dropping 'Class' column:
   Student  English  Science
0   Alice       84       56
1    Riya       78       78
2    Aman       70       90
3    Hari       81       67

After renaming column:
   Student Class  English  Science_Marks
0   Alice    9A       84             56
1    Riya    6C       78             78
2    Aman    9A       70             90
3    Hari    6C       81             67

After dropping duplicates:
   Student Class  English  Science
0   Alice    9A       84       56
1    Riya    6C       78       78
2    Aman    9A       70       90
3    Hari    6C       81       67

After resetting index:
   Student Class  English  Science
0   Alice    9A       84       56
1    Hari    6C       81       67
2    Riya    6C       78       78
3    Aman    9A       70       90

In [121]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan"],
    "Marks": [80, 75, 90]
})

# Increase marks to 100 where marks are greater than 85
df.loc[df["Marks"] > 85, "Marks"] = 100

print(df)

    Name  Marks
0   Aman     80
1   Riya     75
2  Karan    100

In [122]:
df.loc[df["Marks"] > 40, "Result"] = "Pass"
print(df)

    Name  Marks Result
0   Aman     80   Pass
1   Riya     75   Pass
2  Karan    100   Pass